name: Manually triggered workflow
on:
  workflow_dispatch
jobs:
  transition-issue-cr-rejected:
    name: Transition Ticket CR Rejected
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Login
      id: login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Find Issue Key
      id: jira
      uses: atlassian/gajira-find-issue-key@master
      with:
        from: branch

    - name: Transition Ticket CR Rejected
      id: transition
      uses: atlassian/gajira-transition@master
      with:
        issue: ${{ steps.jira.outputs.issue }}
        transition: "CR Rejected"

    - name: Comment on issue
      id: comment
      uses: atlassian/gajira-comment@master
      with:
        issue: ${{ steps.jira.outputs.issue }}
        comment: repository ${{ github.event.repository.full_name }}