on:
  pull_request:
    types: [REQUEST_CHANGES, assigned]

name: Transition Ticket CR Rejected
jobs:
  transition-issue-cr-rejected:
    name: Transition Ticket CR Rejected
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Find Issue Key
      uses: atlassian/gajira-find-issue-key@master
      with:
        from: branch

    - name: Transition Ticket CR Rejected
      uses: atlassian/gajira-transition@master
      with:
        issue: ${{ steps.create.outputs.issue }}
        transition: "CR Rejected"